### ISSUE TITLE
"very important security fix" for joomla 3.4.x: also relevant for Joomla 2.5?

### ISSUE THREAD

**Issue by level420** [PhilETaylor/Joomla2.5.999#3]
Regarding the latest security announcement: https://www.joomla.org/announcements/release-news/5633-important-security-announcement-pre-release.html 

Does someone know if joomla 2.5 (and joomla 1.5) are also affected?

Thank you for sharing information

Regards

**Comment by PhilETaylor** [comment]
I am part of the official Joomla Security Strike Team and one of the guys that has been investigating/fixing this announced issue. 

At this time I will not provide any further information before the official release tomorrow.

**Comment by level420** [comment]
Thank you Phil. I really appreciate you answer, which I hope, implies that the strike team will help us also creating a patch for joomla 1.5 or joomla 2.5 if affected.

Good luck for the patch release tomorrow.

Regards
