### ISSUE TITLE
"very important security fix" for joomla 3.4.x: also relevant for Joomla 2.5?

### ISSUE THREAD

**Issue by level420** [PhilETaylor/Joomla2.5.999#4]
Hi Phil!

As the security fix is now available: does it also affect joomla 2.5 and/or joomla 1.5?

Thank you for answering.

Regards.

**Comment by PhilETaylor** [comment]
The versions effected are announced in the joomla.org article

**Comment by wilsonge** [comment]
*affected :P

**Comment by PhilETaylor** [comment]
im busy :)

**Comment by level420** [comment]
@PhilETaylor yes, I've read the announcement, but it is not clear to me if the announcements just list version which are not end of life.

So I'll (I assume WE) really would appreciate a clear statement related to joomla 1.5 and joomla 2.5.

Thank you.

Regards.

**Comment by PhilETaylor** [comment]
Joomla 1.5 and Joomla 2.5 are end of life and should not be used. 

The official announcement clearly states:
High Priority - Core - SQL Injection (affecting Joomla 3.2 through 3.4.4) 
Medium Priority - Core - ACL Violations (affecting Joomla 3.2 through 3.4.4) 
Medium Priority - Core - ACL Violations (affecting Joomla 3.0 through 3.4.4)

**Comment by level420** [comment]
Thank you Phil,

but I think I have to ask elsewhere, as it seems that you are not allowed or not willing to answer the direct question.

Regards

**Comment by infograf768** [comment]
2.5 is not affected.

**Comment by level420** [comment]
@infograf768 
That's a direct answer! Thank you!
And what about 1.5?

**Comment by beat** [comment]
@level420 Probably this should answer your question: The announcement is clear: That critical vulnerability "affects Joomla 3.2 to 3.4.4".

However, you should in all cases plan to upgrade to Joomla latest asap, and in the mean time keep an eye on this 1.5.99 and 2.5.99 repo, as it is maintained by security experts on their free time, but only for critical vulnerabilities.

**Comment by level420** [comment]
@beat yes, even if some of you may doubt that I can read, but it is not clear to me if the recent announcements still would report if the vulnerabilities also affect end of life products.

**Comment by mbabker** [comment]
The security team does not actively test non-supported software platforms for security issues; just as stated in the title they are no longer supported.  With that said though, and being very clear about the subject matter, the critical security vulnerability cannot and does not affect any version of Joomla earlier than 3.2.

Regarding the other two notices published, no, 2.5 is not affected.  Given the scope of change between 1.5 and 2.5, without dedicated testing a guaranteed answer can't be given for that branch but if 2.5 is not affected it's safe to assume 1.5 is OK.

**Comment by level420** [comment]
@mbabker Thank you for your answer. 
I would thank the joomla team for their great work and a wonderful CMS.
Regards.

I'll be quiet now ;-)

**Comment by beat** [comment]
I'm pretty sure that Joomla 1.0.15 and Mambo are not affected by those 3 vulnerabilities either (no guarantee as usual).
