### ISSUE TITLE
error after 2.5 upgrade

### ISSUE THREAD

**Issue by openaspace** [PhilETaylor/Joomla2.5.999#7]
Hello, 
after upgrading my joomla to yours patch I have this error:

Notice: Trying to get property of non-object in /public_html/website.com/libraries/joomla/factory.php on line 223

**Comment by BettonDesign** [comment]
Thank you for your email.

Betton Design is now closed for Christmas and will re-open on Monday 4th January. Emails will be checked periodically over the Christmas period but only critical work will be carried out.

Have a happy Christmas and new year.

**Comment by PhilETaylor** [comment]
logout and login again - does that fix it?

**Comment by openaspace** [comment]
it occour in the public website without login,
restoring the original debug.php it disappear

**Comment by PhilETaylor** [comment]
Are you sure you have debugging disabled on this live site? The debug plugin should not fire unless enabled.

**Comment by openaspace** [comment]
yes it is disabled

**Comment by PhilETaylor** [comment]
Im sorry - I cannot replicate with a clean install even with Error Reporting on Maximum in Global Config

**Comment by openaspace** [comment]
thanks you for sharing your works

**Comment by PhilETaylor** [comment]
try truncating your #__sessions table in the database and see if that has any effect.

**Comment by PhilETaylor** [comment]
I have now run lots of different tests to try and replicate this problem but I cannot - sorry 

Please ensure you are using the right files, either the official "unoffical" patch or the files provided in this repo which are exact copies.
