### ISSUE TITLE
Major vulnerability patched in 3.6.4

### ISSUE THREAD

**Issue by lyquix-owner** [PhilETaylor/Joomla2.5.999#8]
Is there a need to patch 2.5.x to fix vulnerabilities fixed with 3.6.4?

https://www.joomla.org/announcements/release-news/5678-joomla-3-6-4-released.html

It seems like the code the causes the issues of account creation has been present since 1.6, here:

/components/com_users/controllers/user.php
UsersControllerUser::register()
https://github.com/PhilETaylor/Joomla2.5.999/blob/master/components/com_users/controllers/user.php#L105

I don't know if the other vulnerability (elevated privileges) affects 2.5.x.

**Comment by simpleenigma** [comment]
Don;t quote me on this, but I read that is only affected 3.4.4 through 3.6.3

**Comment by PhilETaylor** [comment]
How about you go and READ THE ANNOUNCEMENT for yourself. 

https://www.joomla.org/announcements/release-news/5678-joomla-3-6-4-released.html

> affecting Joomla! 3.4.4 through 3.6.3

Dont you think the JSST went through each.and.every.damn.version to test this?? What did you do with your weekend - I know I sure as hell was testing security vulnerabilities in Joomla... :-)

**Comment by PhilETaylor** [comment]
@mbabker come over here and confirm this please :) :)

**Comment by mbabker** [comment]
Quoting @simpleenigma: 

> only affected 3.4.4 through 3.6.3

Just as the announcement says.

**Comment by lyquix-owner** [comment]
@PhilETaylor: I am only asking a question. No need to be rude. 

2.5.x is no longer supported by Joomla so I don't expect them to check it or test it. I am trying to contribute.

**Comment by simpleenigma** [comment]
LOL

**Comment by PhilETaylor** [comment]
**"No longer supported"** but there are MANY people that do A LOT behind closed doors to ensure people running it are STILL secure... Not that they get paid for it, or respect for it, but because its the right thing to do...

**Comment by lyquix-owner** [comment]
I appreciate the work of every contributor to Joomla. I try to contribute as well. We are all volunteers. You should evaluate how you interact with other members of this community, your response to my post was rude and inappropriate. It doesn't bother me, but it worries me that newcomers are faced with your kind of negative attitude and aggressiveness.
I recommend you read: https://www.joomla.org/about-joomla/the-project/code-of-conduct.html

**Comment by PhilETaylor** [comment]
This is my repo - if you dont like it fork it. 

The announcement made it VERY clear what the facts are.

**Comment by mbabker** [comment]
This isn't an official project space.  Just an effort by someone with a vested interest in ensuring outdated versions are patched as needed.

**Comment by lyquix-owner** [comment]
Understood, good luck

**Comment by PhilETaylor** [comment]
Actually I have no `vested interest` in it at all - I don't own any Joomla 2.5.x sites, because I know better, but there are millions of them out there (so people tell me) that cannot (or cant be bothered) to update them, and so this repo and the 1.5.999 repo exist for those people. 

There is only one Joomla version people should be encouraged to use - and thats the latest one.

**Comment by PhilETaylor** [comment]
We went around in circles like this before - see https://github.com/PhilETaylor/Joomla2.5.999/issues/4 

People need to learn to read announcements and trust the information in them.
