### ISSUE TITLE
J 2.5.x patch for 3.6.5

### ISSUE THREAD

**Issue by webchun** [PhilETaylor/Joomla2.5.999#9]
Is there 2.5.x patch available for issue addressed on 3.6.5? Thanks

**Comment by StefanSTS** [comment]
There is a patch for testing purpose from the VirtueMart team that builds on the J 3.6.5 files. Still in testing phase.
http://dev.virtuemart.net/attachments/download/1036/Joomla2.5.28-20161214PATCH.zip
It includes the old patches from Dec 2015, so you might get logged out, if you apply the patch.

**Comment by PhilETaylor** [comment]
> Is there 2.5.x patch available for issue addressed on 3.6.5? Thanks

No. This project is not going to provide patches.

**Comment by webchun** [comment]
Thanks @StefanSTS 👍  Do you know where I can follow the progress of the work?

**Comment by StefanSTS** [comment]
@webchun There is a news release from VM. There is a comment section, so user input might be there.
https://virtuemart.net/news/latest-news/478-joomla-security-release-3-6-5-and-patch-for-joomla-2-5-28
